### ISSUE TITLE
Segmentation Fault in pt_console

### ISSUE THREAD

**Issue by Danaus214** [PeteyCodes/DarkCaverns#4]
Hey! I'm not really sure if this is my fault or something I've done, but I see it isn't changed in the latest master branch or SDL2 update branch.

It's probably something I did wrong, I am not sure what though? Any help would be greatly appreciated.

I am on Day 4 video in the last 3rd of the video.

![segfault](https://user-images.githubusercontent.com/38461482/39082332-71d3580a-451f-11e8-9e09-2d820d2cbcf8.png)

I am using VSCode with MingGW, and the latest version of SDL2. I believe i used the i686 version? Maybe that is why. I am not sure. I also put SDL right inside with MinGW32's libraries and includes.

I read about segmentation faults and I guess it's because *pixel isn't initialized to anything like an array? 

Must be the version of SDL i used or something.

If not though please let me know :D

**Comment by Danaus214** [comment]
Hmm can't seem to find what the problem is. It also segment faults if I add a *pixel array too I'm not sure what to do here.

Would it be possible to know exactly what you used and how you set up your development environment by any chance?

**Comment by Danaus214** [comment]
Alright so I figured out what the problem was.

On day 4p1 When you add the VISIBILITY Component to the Switch statement in game.c

and you change these, 

&positionComps[obj->id];
&visibilityComps[obj->id];

to 

&pos;
&vis;

It won't allow that and throws that segmentation fault.

Now I think it's because of this.

```
void addComponentToGameObject(GameObject *obj, GameComponent comp, void *compData)
{
    assert(obj->id != -1);

    /* Declarartions */

    /* << as per >> earlier problem, cannot add Label (ie "Position") to 
    * declarations, only statements
    */

    Visibility *vis = NULL;
    Visibility *visData = NULL;
    Position *pos = NULL;
    Position *posData = NULL;

    switch(comp)
    {
        case COMP_POSITION:
            pos = &positionComps[obj->id];
            posData = (Position *)compData;
            pos->objectId = obj->id;
            pos->x = posData->x;
            pos->y = posData->y;

            obj->components[comp] = &positionComps[obj->id];
            break;                  &visibilityComps[obj->id];

        case COMP_VISIBILITY:
            vis = &visibilityComps[obj->id];
            visData = (Visibility *)compData;
            vis->objectId = obj->id;
            vis->glyph = visData->glyph;
            vis->fgColor = visData->fgColor;
            vis->bgColor = visData->bgColor;

            obj->components[comp] = &visibilityComps[obj->id];
            break;

        default:
            assert(1 == 0);
    }
}
```

These lines specifically:
```

    Visibility *vis = NULL;
    Visibility *visData = NULL;
    Position *pos = NULL;
    Position *posData = NULL;
```

Now if I don't initialize those 4 before the Switch Statement and use the code like you had it from the beginning of day 1.

```void addComponentToGameObject(GameObject *obj, GameComponent comp, void *compData)
{
    assert(obj->id != -1);

    /* Declarartions */

    /* << as per >> earlier problem, cannot add Label (ie "Position") to 
    * declarations, only statements
    */

    // Position *pos = NULL;
    // Position *posData = NULL;

    // Visibility *vis = NULL;
    // Visibility *visData = NULL;
    

    switch(comp)
    {
        case COMP_POSITION:
            // pos = &positionComps[obj->id];
            // posData = (Position *)compData;
            Position *pos = &positionComps[obj->id];
            Position *posData = (Position *)compData;
            pos->objectId = obj->id;
            pos->x = posData->x;
            pos->y = posData->y;

            obj->components[comp] = &positionComps[obj->id];
            break;                  &visibilityComps[obj->id];

        case COMP_VISIBILITY:
            // vis = &visibilityComps[obj->id];
            // visData = (Visibility *)compData;
            Visibility *vis = &visibilityComps[obj->id];
            Visibility *visData = (Visibility *)compData;
            vis->objectId = obj->id;
            vis->glyph = visData->glyph;
            vis->fgColor = visData->fgColor;
            vis->bgColor = visData->bgColor;

            obj->components[comp] = &visibilityComps[obj->id];
            break;

        default:
            assert(1 == 0);
    }
}
```

If I use that code right there. I get this error.

game.c:101:13: error: a label can only be part of a statement and a declaration is not a statement
             Position *pos = &positionComps[obj->id];

So I have to declare the pointers outside the Switch Statement or else I get that other segmentation fault.

Would anyone happen to know why it's behaving differently for me?

The problem is solved for me now but I'm wondering if I'm going to run into this often, and if I will always be able to remedy it the same way.

**Comment by Danaus214** [comment]
Alright so I figured out what the problem was (lol this sucks I have to write this a second time cause I pressed "back")

So in day 4p1 near the end there when you add VISIBILITY component to the switch statement in addComponentToGameObject(){}, 

and you change

```
&positionComps[obj->id];
&visibilityComps[obj->id];

to

&pos;
&vis;
```

It won't allow that and throws that segmentation fault.

Now I think it is because of this.

```
void addComponentToGameObject(GameObject *obj, GameComponent comp, void *compData)
{
    assert(obj->id != -1);

    /* Declarartions */

    /* << as per >> earlier problem, cannot add Label (ie "Position") to 
    * declarations, only statements
    */

    Position *pos = NULL;
    Position *posData = NULL;

    Visibility *vis = NULL;
    Visibility *visData = NULL;
    

    switch(comp)
    {
        case COMP_POSITION:
            pos = &positionComps[obj->id];
            posData = (Position *)compData;
            pos->objectId = obj->id;
            pos->x = posData->x;
            pos->y = posData->y;

            obj->components[comp] = &positionComps[obj->id];
            break;                  &visibilityComps[obj->id];

        case COMP_VISIBILITY:
            vis = &visibilityComps[obj->id];
            visData = (Visibility *)compData;
            vis->objectId = obj->id;
            vis->glyph = visData->glyph;
            vis->fgColor = visData->fgColor;
            vis->bgColor = visData->bgColor;

            obj->components[comp] = &visibilityComps[obj->id];
            break;

        default:
            assert(1 == 0);
    }
}
```

Now if I write it like that it won't throw the segmentation fault exception.

Specifically because of these lines

```

    Position *pos = NULL;
    Position *posData = NULL;

    Visibility *vis = NULL;
    Visibility *visData = NULL;
```

It won't allow me to declare Position and Visibility inside the switch statement. So if I write it like you had it.

```
void addComponentToGameObject(GameObject *obj, GameComponent comp, void *compData)
{
    assert(obj->id != -1);

    /* Declarartions */

    /* << as per >> earlier problem, cannot add Label (ie "Position") to 
    * declarations, only statements
    */

    // Position *pos = NULL;
    // Position *posData = NULL;

    // Visibility *vis = NULL;
    // Visibility *visData = NULL;
    

    switch(comp)
    {
        case COMP_POSITION:
            // pos = &positionComps[obj->id];
            // posData = (Position *)compData;
            Position *pos = &positionComps[obj->id];
            Position *posData = (Position *)compData;
            pos->objectId = obj->id;
            pos->x = posData->x;
            pos->y = posData->y;

            obj->components[comp] = &pos;
            break;

        case COMP_VISIBILITY:
            // vis = &visibilityComps[obj->id];
            // visData = (Visibility *)compData;
            Visibility *vis = &visibilityComps[obj->id];
            Visibility *visData = (Visibility *)compData;
            vis->objectId = obj->id;
            vis->glyph = visData->glyph;
            vis->fgColor = visData->fgColor;
            vis->bgColor = visData->bgColor;

            obj->components[comp] = &vis;
            break;

        default:
            assert(1 == 0);
    }
}
```

I get this error. And it won't even reach &vis; or &pos;
```

game.c:101:13: error: a label can only be part of a statement and a declaration is not a statement
             Position *pos = &positionComps[obj->id];
             ^~~~~~~~
```

So I am required to use 

```
    Position *pos = NULL;
    Position *posData = NULL;

    Visibility *vis = NULL;
    Visibility *visData = NULL;
```

Which leads me to not be able to use

&vis; and &pos;

Which leads to the segmentation error.

My problem is solved by declaring the pointers above the switch statement. But is that going to lead to problems in the future as I follow along? Does anyone know why that is happening in the first place?

**Comment by Danaus214** [comment]
Alright I guess I solved it. I am not very good with pointers and references but I gave it a try mostly guessing but a tiny bit of rationalizing about it I decided to try this instead.

*&pos;
*&vis;

and success!

Problem solved I believe. I guess I will close this now. :grin:

**Comment by PeteyCodes** [comment]
I think the problem is that your compiler (mingw) doesn't fully support the c99 standard, which will end up causing you more problems and force you to rewrite more code as you progress through the codebase. You might want to consider switching to the C compiler that comes with Visual Studio (if on Windows), or gcc or clang on linux/MacOS.
